export const RESOURCE_TYPES = Object.freeze(['sheep', 'food', 'money']);
const RESOURCE_DEFINITIONS=['sheep','food','money','grace'].flatMap(type=>Array.from({length:9},(_,index)=>Object.freeze({definitionId:`${type}-${index+1}`,kind:'resource',type,number:index+1,name:type==='grace'?`恩典 ${index+1}`:undefined,image:`assets/cards/${type}-${index+1}.png`,copies:type==='grace'?1:3})));
export const MIRACLE_DEFINITIONS=Object.freeze([
Object.freeze({definitionId:'miracle-01',kind:'miracle',name:'回轉歸向',tags:Object.freeze(['新生']),text:'改變出牌方向，然後你抽1張牌',image:'assets/miracles/miracle-01.png',copies:1}),
Object.freeze({definitionId:'miracle-02',kind:'miracle',name:'行曠野之路',tags:Object.freeze(['新生']),text:'將此牌置於你的效果區。你下一張成功打出的物資牌數字+3，且可超過原本的數字上限。成功打出物資牌後，你棄置此牌',image:'assets/miracles/miracle-02.png',copies:1}),
Object.freeze({definitionId:'miracle-03',kind:'miracle',name:'荊棘冠冕',tags:Object.freeze(['新生']),text:'將此牌置於你的效果區。你下一張成功打出的物資牌無視出牌限制。成功打出物資牌後，你棄置此牌',image:'assets/miracles/miracle-03.png',copies:1}),
Object.freeze({definitionId:'miracle-04',kind:'miracle',name:'於水中重生',tags:Object.freeze(['流轉','新生']),text:'你棄置全部手牌，然後抽取等量的牌',image:'assets/miracles/miracle-04.png',copies:1}),
Object.freeze({definitionId:'miracle-05',kind:'miracle',name:'如風吹來',tags:Object.freeze(['流轉','火種']),text:'你選擇：棄置1至3張手牌，然後抽取等量的牌 或 不棄置手牌，獲得3點火種',image:'assets/miracles/miracle-05.png',copies:1}),
Object.freeze({definitionId:'miracle-06',kind:'miracle',name:'所望之實底',tags:Object.freeze(['洞察']),text:'你查看牌庫頂3張牌，選擇其中1張加入手牌，其餘牌以任意順序置於牌庫底',image:'assets/miracles/miracle-06.png',copies:1}),
Object.freeze({definitionId:'miracle-07',kind:'miracle',name:'行向水深之處',tags:Object.freeze(['洞察','新生']),text:'你依序展示牌庫頂的牌，直到展示出3種不同牌型或共展示5張為止。選擇其中1張加入手牌，其餘牌以任意順序置於牌庫底',image:'assets/miracles/miracle-07.png',copies:1}),
Object.freeze({definitionId:'miracle-10',kind:'miracle',name:'恰如飛鳥經過',tags:Object.freeze(['共鳴','流轉']),text:'你選擇1名其他玩家。若你與該玩家皆有手牌，你們各選擇1張手牌並同時展示。若雙方皆同意，則交換這2張牌；若任一方不同意，則收回展示的牌。若交換的牌型不同，你與該玩家各獲得3點火種',image:'assets/miracles/miracle-10.png',copies:1}),
Object.freeze({definitionId:'miracle-13',kind:'miracle',name:'在黎明前叩門',tags:Object.freeze(['洞察','新生']),text:'將此牌置於你的效果區。你下一次因效果抽牌時，抽牌數量+1。抽牌後，你棄置1張手牌，然後棄置此牌',image:'assets/miracles/miracle-13.png',copies:1}),
Object.freeze({definitionId:'miracle-16',kind:'miracle',cardType:'miracle',reaction:true,name:'越過長夜',tags:Object.freeze(['應對','庇護']),text:'【應對】當你即將受到災難效果時，你可以打出此牌：你免疫該次效果',image:'assets/miracles/miracle-16.png',copies:1}),
Object.freeze({definitionId:'miracle-17',kind:'miracle',cardType:'miracle',reaction:true,name:'替罪羊',tags:Object.freeze(['應對','共鳴']),text:'【應對】當另一名玩家成為災難目標時，你可以打出此牌：將該災難對他的效果轉移給你，且你不能免疫。若你因此失去火種或棄置手牌，將此牌置於你的效果區。你下一次受到災難時，少失去4點火種或少棄置1張手牌，成功後你棄置此牌',image:'assets/miracles/miracle-17.png',copies:1}),
Object.freeze({definitionId:'miracle-18',kind:'miracle',cardType:'miracle',reaction:true,name:'空墳墓',tags:Object.freeze(['應對','新生']),text:'【應對】當你即將因災難效果失去火種時，你可以打出此牌：正常失去火種後，你每實際失去3點火種，你抽1張牌，最多抽2張。',image:'assets/miracles/miracle-18.png',copies:1}),
Object.freeze({definitionId:'miracle-19',kind:'miracle',cardType:'miracle',reaction:true,reactionOnly:true,name:'拆毀堅固營壘',tags:Object.freeze(['應對','新生']),text:'【應對】當你即將受到具有2項及以上效果的災難時，你可以打出此牌：選擇其中1項效果，使其對你無效；其餘效果正常結算。結算後，你棄置1張手牌，然後抽1張牌。',image:'assets/miracles/miracle-19.png',copies:1}),
Object.freeze({definitionId:'miracle-20',kind:'miracle',cardType:'miracle',reaction:true,name:'勝過死亡',tags:Object.freeze(['應對','新生']),text:'【應對】當你的手牌數量或火種即將因效果從1以上降至0時，你可以打出此牌：你可選擇使其保留1。',image:'assets/miracles/miracle-20.png',copies:1}),
Object.freeze({definitionId:'miracle-22',kind:'miracle',name:'雨幕之下',tags:Object.freeze(['庇護','新生']),text:'你選擇1名玩家，棄置其效果區中的1張持續災難牌，或清除其1個【負面】。若成功，該玩家獲得2點火種',image:'assets/miracles/miracle-22.png',copies:1}),]);
export const DISASTER_DEFINITIONS=Object.freeze([
Object.freeze({definitionId:'disaster-01',kind:'disaster',name:'方舟之外',tags:Object.freeze(['群體','掠奪']),text:'每名玩家選擇自己手中的1種物資種類並保留該種類的物資牌，然後從其他種類的物資牌中棄置2張；若不足2張，則全部棄置',image:'assets/disasters/disaster-01.png',copies:1}),
Object.freeze({definitionId:'disaster-02',kind:'disaster',name:'謊言與試探',tags:Object.freeze(['多體','掠奪']),text:'你選擇2名其他玩家。這2名玩家各自選擇1張手牌並展示，你選擇其中1張取得；另一張由原持有者收回手牌',image:'assets/disasters/disaster-02.png',copies:1}),
Object.freeze({definitionId:'disaster-07',kind:'disaster',name:'灰與燼',tags:Object.freeze(['群體','熄滅','蔓延']),effects:Object.freeze([Object.freeze({effectId:'lose-fire',scope:'each-player',text:'每名玩家失去3點火種'}),Object.freeze({effectId:'miracle-fire-reduction',scope:'each-player',duration:'round',text:'直到本輪結束，所有玩家因神蹟效果獲得的火種減少2點，最低為0'})]),text:'每名玩家失去3點火種。直到本輪結束，所有玩家因神蹟效果獲得的火種減少2點，最低為0。',image:'assets/disasters/disaster-07.png',copies:1}),
Object.freeze({definitionId:'disaster-08',kind:'disaster',name:'積財寶在地上',tags:Object.freeze(['單體','熄滅']),text:'你選擇1名其他玩家。該玩家每持有5點火種，則失去2點火種，最多失去10點。若該玩家持有的火種不足5點，則不受此效果影響',image:'assets/disasters/disaster-08.png',copies:1}),
Object.freeze({definitionId:'disaster-09',kind:'disaster',name:'瘟疫',tags:Object.freeze(['單體','蔓延']),negative:true,duration:'round',text:'【負面】放置於任意玩家的效果區。本輪內，你成功打出的群羊牌數字-2，最低為0。成功打出群羊牌後，依出牌方向將此牌移至下一名玩家的效果區。本輪結束時，棄置此牌',image:'assets/disasters/disaster-09.png',copies:1})]);
export const CARD_DEFINITIONS=Object.freeze([...RESOURCE_DEFINITIONS,...MIRACLE_DEFINITIONS,...DISASTER_DEFINITIONS]);export const DEFINITION_BY_ID=new Map(CARD_DEFINITIONS.map(d=>[d.definitionId,d]));
export function createResourceDeck(){const cards=[];for(const d of CARD_DEFINITIONS)for(let copy=1;copy<=d.copies;copy++)cards.push({instanceId:`${d.definitionId}#${copy}`,definitionId:d.definitionId});return cards;}export function getDefinition(card){const d=DEFINITION_BY_ID.get(card?.definitionId);if(!d)throw new Error(`Unknown card definition: ${card?.definitionId}`);return d;}export function effectiveType(card,declaredType=card?.declaredType){const d=getDefinition(card);if(d.kind!=='resource')return null;return d.type==='grace'?declaredType:d.type;}export function beats(challenger,current){return(challenger==='sheep'&&current==='food')||(challenger==='food'&&current==='money')||(challenger==='money'&&current==='sheep');}export function isLegalResourcePlay(card,currentResource,declaredType){const d=getDefinition(card);if(d.kind!=='resource')return false;const type=d.type==='grace'?declaredType:d.type;if(!RESOURCE_TYPES.includes(type))return false;if(!currentResource)return true;if(type===currentResource.type)return d.number>=currentResource.number;return beats(type,currentResource.type);}