import { GameController } from '../controller/game-controller.js';
import { getDefinition, RESOURCE_TYPES } from '../game/cards.js';
import { getNormalActions } from '../game/game.js';

const originalAct=GameController.prototype.act;
const originalRunAiTurn=GameController.prototype.runAiTurn;
const originalPrepare=GameController.prototype.prepare;
let pending=null;
const names={sheep:'群羊',food:'糧食',money:'金錢'};
const resources=p=>p.hand.filter(c=>{const d=getDefinition(c);return d.kind==='resource'&&RESOURCE_TYPES.includes(d.type);});
function autoChoice(p){const cards=resources(p);if(!cards.length)return{keepType:null,discardIds:[]};const counts=Object.fromEntries(RESOURCE_TYPES.map(t=>[t,cards.filter(c=>getDefinition(c).type===t).length]));const keepType=[...RESOURCE_TYPES].sort((a,b)=>counts[b]-counts[a])[0];return{keepType,discardIds:cards.filter(c=>getDefinition(c).type!==keepType).slice(0,2).map(c=>c.instanceId)};}
function allChoices(controller,humanChoice){return Object.fromEntries(controller.state.players.map(p=>[p.playerId,p.type==='human'?humanChoice:autoChoice(p)]));}
function ensureUi(){if(document.querySelector('#ark-choice-overlay'))return;const style=document.createElement('style');style.textContent=`#ark-choice-overlay[hidden]{display:none!important}#ark-choice-overlay{position:fixed;inset:0;z-index:32000;display:grid;place-items:center;background:#050807d4;backdrop-filter:blur(8px);padding:12px}.ark-panel{width:min(760px,94vw);max-height:92vh;overflow:auto;box-sizing:border-box;padding:20px;border:1px solid #d7bd7a55;border-radius:20px;background:linear-gradient(145deg,#171b18,#0c100e);box-shadow:0 28px 80px #000b;color:#eee8d8}.ark-panel h2{margin:4px 0 6px;font-size:24px}.ark-panel p{opacity:.82}.ark-types,.ark-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.ark-type,.ark-card,.ark-confirm{border:1px solid #d7bd7a55;border-radius:12px;background:#ffffff08;color:inherit;padding:10px;cursor:pointer}.ark-type.selected,.ark-card.selected{background:#d7bd7a22;border-color:#d7bd7a}.ark-card img{width:auto;height:min(28vh,190px);max-width:100%;object-fit:contain;display:block;margin:auto}.ark-confirm{display:block;margin:12px auto 0;padding:11px 20px}.ark-confirm:disabled{opacity:.35;cursor:not-allowed}@media(max-width:650px){.ark-types{grid-template-columns:1fr}.ark-cards{grid-template-columns:repeat(2,1fr)}}`;document.head.append(style);const o=document.createElement('div');o.id='ark-choice-overlay';o.hidden=true;document.body.append(o);}
function close(){const o=document.querySelector('#ark-choice-overlay');if(o)o.hidden=true;pending=null;}
function finish(humanChoice){const p=pending;if(!p)return;const action={...p.action,groupChoices:allChoices(p.controller,humanChoice)};close();return originalAct.call(p.controller,action,p.token);}
function showDiscard(keepType){if(!pending)return;const human=pending.controller.state.players.find(p=>p.type==='human'),eligible=resources(human).filter(c=>getDefinition(c).type!==keepType),required=Math.min(2,eligible.length),selected=[],o=document.querySelector('#ark-choice-overlay');if(required===0)return finish({keepType,discardIds:[]});o.innerHTML=`<article class="ark-panel"><span>方舟之外 · 群體｜掠奪</span><h2>棄置 ${required} 張其他種類物資</h2><p>你選擇保留「${names[keepType]}」。神蹟、災難與恩典不在此效果的棄牌範圍。</p><div class="ark-cards"></div><button class="ark-confirm" disabled>確認棄置</button></article>`;const host=o.querySelector('.ark-cards'),confirm=o.querySelector('.ark-confirm');for(const card of eligible){const d=getDefinition(card),b=document.createElement('button');b.className='ark-card';b.innerHTML=`<img src="${d.image}" alt="${names[d.type]} ${d.number}"><strong>${names[d.type]} ${d.number}</strong>`;b.onclick=()=>{const i=selected.indexOf(card.instanceId);if(i>=0){selected.splice(i,1);b.classList.remove('selected');}else if(selected.length<required){selected.push(card.instanceId);b.classList.add('selected');}confirm.disabled=selected.length!==required;};host.append(b);}confirm.onclick=()=>finish({keepType,discardIds:selected});}
function showChoice(){ensureUi();if(!pending)return;const human=pending.controller.state.players.find(p=>p.type==='human'),cards=resources(human),types=[...new Set(cards.map(c=>getDefinition(c).type))],o=document.querySelector('#ark-choice-overlay');if(!cards.length){return finish({keepType:null,discardIds:[]});}if(types.length===1){return finish({keepType:types[0],discardIds:[]});}o.innerHTML=`<article class="ark-panel"><span>災難 · 群體｜掠奪</span><h2>方舟之外</h2><p>選擇 1 種你要保留的物資種類。之後從其他物資種類中棄置 2 張；不足 2 張則全部棄置。遊戲會停在這裡等你。</p><div class="ark-types"></div></article>`;const host=o.querySelector('.ark-types');for(const type of types){const count=cards.filter(c=>getDefinition(c).type===type).length,b=document.createElement('button');b.className='ark-type';b.innerHTML=`<strong>${names[type]}</strong><br>${count} 張`;b.onclick=()=>showDiscard(type);host.append(b);}o.hidden=false;}
function begin(controller,action,token){controller.cancelTimer();pending={controller,action,token};showChoice();return{ok:false,pendingChoice:true,state:controller.state};}
GameController.prototype.act=function(action,token=this.snapshot()){if(action?.type==='playMiracle'){const actor=this.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);if(actor?.type==='human'&&card&&getDefinition(card).definitionId==='disaster-01')return begin(this,action,token);}return originalAct.call(this,action,token);};
GameController.prototype.prepare=function(){if(pending?.controller===this){this.cancelTimer();this.safeRender(getNormalActions(this.state));return;}return originalPrepare.call(this);};
GameController.prototype.runAiTurn=function(generation,playerId){if(pending?.controller===this){this.cancelTimer();return;}if(generation!==this.generation||!this.state||this.state.gameOver)return;const actor=this.state.players.find(p=>p.playerId===this.state.currentPlayer);if(actor?.type==='ai'&&actor.playerId===playerId){const action=getNormalActions(this.state)[0],card=action?.type==='playMiracle'?actor.hand.find(c=>c.instanceId===action.instanceId):null;if(card&&getDefinition(card).definitionId==='disaster-01'){const human=this.state.players.find(p=>p.type==='human');if(resources(human).length){begin(this,action,this.snapshot());return;}const result=originalAct.call(this,{...action,groupChoices:allChoices(this,autoChoice(human))},this.snapshot());return result;}}return originalRunAiTurn.call(this,generation,playerId);};
