import { GameController } from '../controller/game-controller.js';
import { getDefinition, RESOURCE_TYPES } from '../game/cards.js';
import { getNormalActions } from '../game/game.js';

const SCAPEGOAT_ID='miracle-17';
const originalAct=GameController.prototype.act;
const originalRunAiTurn=GameController.prototype.runAiTurn;
const originalPrepare=GameController.prototype.prepare;
let pending=null;
const names={sheep:'群羊',food:'糧食',money:'金錢'};
const resources=p=>p.hand.filter(c=>{const d=getDefinition(c);return d.kind==='resource'&&RESOURCE_TYPES.includes(d.type);});
const hasScapegoat=p=>p.effects.some(c=>c.definitionId===SCAPEGOAT_ID);
const overlayVisible=()=>{const o=document.querySelector('#ark-choice-overlay');return !!o&&!o.hidden;};
const actorIsHuman=()=>{if(!pending)return false;return pending.controller.state.players.find(p=>p.playerId===pending.action.playerId)?.type==='human';};
function autoChoice(p){const cards=resources(p);if(!cards.length)return{keepType:null,discardIds:[]};const counts=Object.fromEntries(RESOURCE_TYPES.map(t=>[t,cards.filter(c=>getDefinition(c).type===t).length]));const keepType=[...RESOURCE_TYPES].sort((a,b)=>counts[b]-counts[a])[0];return{keepType,discardIds:cards.filter(c=>getDefinition(c).type!==keepType).slice(0,2).map(c=>c.instanceId)};}
function allChoices(controller,humanChoice){return Object.fromEntries(controller.state.players.map(p=>[p.playerId,p.type==='human'?humanChoice:autoChoice(p)]));}
function ensureUi(){if(document.querySelector('#ark-choice-overlay'))return;const style=document.createElement('style');style.textContent=`#ark-choice-overlay[hidden]{display:none!important}#ark-choice-overlay{position:fixed;inset:0;z-index:32000;display:grid;place-items:center;background:#050807d4;backdrop-filter:blur(8px);padding:12px}.ark-panel{width:min(760px,94vw);max-height:92vh;overflow:auto;box-sizing:border-box;padding:20px;border:1px solid #d7bd7a55;border-radius:20px;background:linear-gradient(145deg,#171b18,#0c100e);box-shadow:0 28px 80px #000b;color:#eee8d8}.ark-panel h2{margin:4px 0 6px;font-size:24px}.ark-panel p{opacity:.82}.ark-types,.ark-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.ark-type,.ark-card,.ark-confirm,.ark-cancel,.ark-back{border:1px solid #d7bd7a55;border-radius:12px;background:#ffffff08;color:inherit;padding:10px;cursor:pointer}.ark-type.selected,.ark-card.selected{background:#d7bd7a22;border-color:#d7bd7a}.ark-card img{width:auto;height:min(28vh,190px);max-width:100%;object-fit:contain;display:block;margin:auto}.ark-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:12px}.ark-confirm:disabled{opacity:.35;cursor:not-allowed}.ark-cancel{border-color:#c99b6b66}@media(max-width:650px){.ark-types{grid-template-columns:1fr}.ark-cards{grid-template-columns:repeat(2,1fr)}}`;document.head.append(style);const o=document.createElement('div');o.id='ark-choice-overlay';o.hidden=true;document.body.append(o);}
function close(){const o=document.querySelector('#ark-choice-overlay');if(o)o.hidden=true;pending=null;}
function cancelOwnPlay(){if(!pending||!actorIsHuman())return;const controller=pending.controller;close();controller.safeRender(getNormalActions(controller.state));}
function consumeShield(state,humanId,restoreId){const human=state.players.find(p=>p.playerId===humanId),effect=human?.effects.find(c=>c.definitionId===SCAPEGOAT_ID);if(!human||!effect)return;if(restoreId){const i=state.discardPile.findIndex(c=>c.instanceId===restoreId);if(i>=0)human.hand.push(state.discardPile.splice(i,1)[0]);}human.effects=human.effects.filter(c=>c.instanceId!==effect.instanceId);state.discardPile.push(effect);}
function finish(humanChoice){const p=pending;if(!p)return;const human=p.controller.state.players.find(x=>x.type==='human'),shielded=hasScapegoat(human);let coreChoice=humanChoice,restoreId=null;if(shielded&&humanChoice.keepType){const eligible=resources(human).filter(c=>getDefinition(c).type!==humanChoice.keepType);const normalRequired=Math.min(2,eligible.length);if(normalRequired>humanChoice.discardIds.length){restoreId=eligible.find(c=>!humanChoice.discardIds.includes(c.instanceId))?.instanceId??null;if(restoreId)coreChoice={...humanChoice,discardIds:[...humanChoice.discardIds,restoreId]};}}
const action={...p.action,groupChoices:allChoices(p.controller,coreChoice)};const controller=p.controller,token=p.token,humanId=human.playerId;close();const result=originalAct.call(controller,action,token);if(result?.ok&&shielded&&(humanChoice.discardIds.length<coreChoice.discardIds.length)){consumeShield(result.state,humanId,restoreId);controller.state=result.state;controller.safeRender(getNormalActions(controller.state));}return result;}
function showDiscard(keepType){if(!pending)return;const human=pending.controller.state.players.find(p=>p.type==='human'),eligible=resources(human).filter(c=>getDefinition(c).type!==keepType),normalRequired=Math.min(2,eligible.length),shielded=hasScapegoat(human)&&normalRequired>0,required=Math.max(0,normalRequired-(shielded?1:0)),selected=[],o=document.querySelector('#ark-choice-overlay');if(required===0)return finish({keepType,discardIds:[]});o.innerHTML=`<article class="ark-panel"><span>方舟之外 · 群體｜掠奪</span><h2>棄置 ${required} 張其他種類物資</h2><p>你選擇保留「${names[keepType]}」。${shielded?'《替罪羊》正在保護你，因此原本應棄置 '+normalRequired+' 張，這次由你選擇實際棄置 '+required+' 張。':'神蹟、災難與恩典不在此效果的棄牌範圍。'}</p><div class="ark-cards"></div><div class="ark-actions"><button class="ark-back">返回上一步</button><button class="ark-confirm" disabled>確認棄置</button>${actorIsHuman()?'<button class="ark-cancel">取消，收回方舟之外</button>':''}</div></article>`;const host=o.querySelector('.ark-cards'),confirm=o.querySelector('.ark-confirm');for(const card of eligible){const d=getDefinition(card),b=document.createElement('button');b.className='ark-card';b.innerHTML=`<img src="${d.image}" alt="${names[d.type]} ${d.number}"><strong>${names[d.type]} ${d.number}</strong>`;b.onclick=()=>{const i=selected.indexOf(card.instanceId);if(i>=0){selected.splice(i,1);b.classList.remove('selected');}else if(selected.length<required){selected.push(card.instanceId);b.classList.add('selected');}confirm.disabled=selected.length!==required;};host.append(b);}o.querySelector('.ark-back').onclick=showChoice;o.querySelector('.ark-cancel')?.addEventListener('click',cancelOwnPlay);confirm.onclick=()=>finish({keepType,discardIds:selected});}
function showChoice(){ensureUi();if(!pending)return;const human=pending.controller.state.players.find(p=>p.type==='human'),cards=resources(human),types=[...new Set(cards.map(c=>getDefinition(c).type))],o=document.querySelector('#ark-choice-overlay');if(!cards.length)return finish({keepType:null,discardIds:[]});o.innerHTML=`<article class="ark-panel"><span>災難 · 群體｜掠奪</span><h2>方舟之外</h2><p>${types.length===1?`你目前只有「${names[types[0]]}」這 1 種一般物資，因此只能保留它；請確認後繼續。`:'選擇 1 種你要保留的物資種類。之後從其他物資種類中棄置 2 張；不足 2 張則全部棄置。'} 遊戲會停在這裡等你。</p><div class="ark-types"></div>${actorIsHuman()?'<div class="ark-actions"><button class="ark-cancel">取消，收回方舟之外</button></div>':''}</article>`;const host=o.querySelector('.ark-types');for(const type of types){const count=cards.filter(c=>getDefinition(c).type===type).length,b=document.createElement('button');b.className='ark-type';b.innerHTML=`<strong>${names[type]}</strong><br>${count} 張${types.length===1?'<br><small>確認保留</small>':''}`;b.onclick=()=>showDiscard(type);host.append(b);}o.querySelector('.ark-cancel')?.addEventListener('click',cancelOwnPlay);o.hidden=false;}
function begin(controller,action,token){controller.cancelTimer();pending={controller,action,token};showChoice();return{ok:false,pendingChoice:true,state:controller.state};}
GameController.prototype.act=function(action,token=this.snapshot()){if(action?.type==='playMiracle'&&!action.groupChoices){const actor=this.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);if(card&&getDefinition(card).definitionId==='disaster-01')return begin(this,action,token);}return originalAct.call(this,action,token);};
GameController.prototype.prepare=function(){if(pending?.controller===this&&overlayVisible()){this.cancelTimer();this.safeRender(getNormalActions(this.state));return;}if(pending?.controller===this&&!overlayVisible())pending=null;return originalPrepare.call(this);};
GameController.prototype.runAiTurn=function(generation,playerId){if(pending?.controller===this&&overlayVisible()){this.cancelTimer();return;}if(pending?.controller===this&&!overlayVisible())pending=null;if(generation!==this.generation||!this.state||this.state.gameOver)return;const actor=this.state.players.find(p=>p.playerId===this.state.currentPlayer);if(actor?.type==='ai'&&actor.playerId===playerId){const actions=getNormalActions(this.state),arkAction=actions.find(action=>{if(action?.type!=='playMiracle')return false;const card=actor.hand.find(c=>c.instanceId===action.instanceId);return card&&getDefinition(card).definitionId==='disaster-01';});if(arkAction)return begin(this,arkAction,this.snapshot());}return originalRunAiTurn.call(this,generation,playerId);};