import { GameController } from '../controller/game-controller.js';
import { getDefinition } from '../game/cards.js';

const CARD_ID='miracle-06';
const previousAct=GameController.prototype.act;
let active=null;

function ensureUi(){if(document.querySelector('#hope-insight-overlay'))return;const style=document.createElement('style');style.textContent=`#hope-insight-overlay[hidden]{display:none!important}#hope-insight-overlay{position:fixed;inset:0;z-index:42000;display:grid;place-items:center;background:#050807b8;backdrop-filter:blur(10px);padding:18px}.hope-panel{width:min(860px,94vw);padding:26px;border:1px solid #d7bd7a55;border-radius:22px;background:linear-gradient(145deg,#171d1af2,#0b100ef2);box-shadow:0 30px 90px #000c;color:#eee8d8}.hope-panel h2{margin:5px 0 8px}.hope-cards{display:flex;justify-content:center;gap:18px;flex-wrap:wrap;margin:22px 0}.hope-card{width:150px;padding:8px;border:2px solid transparent;border-radius:14px;background:#ffffff08;color:inherit;cursor:pointer;transition:.16s}.hope-card:hover{transform:translateY(-8px);border-color:#d7bd7a88}.hope-card img{display:block;width:100%;border-radius:10px}.hope-card span{display:block;margin-top:8px;font-size:12px}.hope-order{display:flex;justify-content:center;gap:18px;align-items:center;margin:22px 0}.hope-order-card{width:140px}.hope-order-card img{display:block;width:100%;border-radius:10px}.hope-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.hope-actions button{padding:11px 17px;border-radius:11px;border:1px solid #d7bd7a66;background:#ffffff0d;color:inherit;cursor:pointer}.hope-actions .primary{background:#d7bd7a;color:#17130b;font-weight:700}.hope-note{opacity:.72;line-height:1.6;text-align:center}`;document.head.append(style);const o=document.createElement('div');o.id='hope-insight-overlay';o.hidden=true;document.body.append(o);}
function close(){const o=document.querySelector('#hope-insight-overlay');if(o)o.hidden=true;active=null;}
function title(card){const d=getDefinition(card);return d.name??`${d.type} ${d.number}`;}
function commit(selectedId,bottomOrderIds){const p=active;if(!p)return;close();previousAct.call(p.controller,{...p.action,selectedCardId:selectedId,bottomOrderIds},p.token);}
function showOrder(selectedId){const {controller}=active,o=document.querySelector('#hope-insight-overlay'),cards=controller.state.deck.slice(0,3),rest=cards.filter(c=>c.instanceId!==selectedId);let order=[...rest];const render=()=>{o.innerHTML=`<article class="hope-panel" role="dialog" aria-modal="true"><span>神蹟 · 洞察</span><h2>安排牌庫底順序</h2><p class="hope-note">你選中的牌會加入手牌。其餘兩張將依左→右順序置於牌庫底。</p><div class="hope-order">${order.map(c=>`<div class="hope-order-card"><img src="${getDefinition(c).image}" alt="${title(c)}"><span>${title(c)}</span></div>`).join('<strong>→</strong>')}</div><div class="hope-actions"><button id="hope-swap">交換順序</button><button id="hope-back">返回重選</button><button class="primary" id="hope-confirm">確認</button></div></article>`;o.querySelector('#hope-swap').onclick=()=>{order.reverse();render();};o.querySelector('#hope-back').onclick=showChoose;o.querySelector('#hope-confirm').onclick=()=>commit(selectedId,order.map(c=>c.instanceId));};render();}
function showChoose(){ensureUi();const {controller}=active,o=document.querySelector('#hope-insight-overlay'),cards=controller.state.deck.slice(0,3);o.innerHTML=`<article class="hope-panel" role="dialog" aria-modal="true"><span>神蹟 · 洞察</span><h2>所望之實底</h2><p class="hope-note">查看牌庫頂 3 張牌。選擇其中 1 張加入手牌，其餘牌再由你安排置於牌庫底。</p><div class="hope-cards"></div><div class="hope-actions"><button id="hope-cancel">取消，放回手牌</button></div></article>`;const host=o.querySelector('.hope-cards');for(const card of cards){const b=document.createElement('button');b.className='hope-card';b.innerHTML=`<img src="${getDefinition(card).image}" alt="${title(card)}"><span>${title(card)}</span>`;b.onclick=()=>showOrder(card.instanceId);host.append(b);}o.querySelector('#hope-cancel').onclick=close;o.hidden=false;}

GameController.prototype.act=function(action,token=this.snapshot()){if(action?.type==='playMiracle'){const actor=this.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);if(actor?.type==='human'&&card?.definitionId===CARD_ID&&!action.selectedCardId){active={controller:this,action,token};showChoose();return{ok:false,pendingChoice:true,state:this.state};}}return previousAct.call(this,action,token);};
