import { GameController } from '../controller/game-controller.js';
import { getDefinition } from '../game/cards.js';

const CARD_IDS=new Set(['miracle-06','miracle-07']);
const previousAct=GameController.prototype.act;
let active=null;
const log=(c,t)=>typeof c.logAi==='function'&&c.logAi(t);

function ensureUi(){if(document.querySelector('#hope-insight-overlay'))return;const style=document.createElement('style');style.textContent=`#hope-insight-overlay[hidden]{display:none!important}#hope-insight-overlay{position:fixed;inset:0;z-index:42000;display:grid;place-items:center;background:#050807b8;backdrop-filter:blur(10px);padding:18px}.hope-panel{width:min(940px,94vw);max-height:92vh;overflow:auto;padding:26px;border:1px solid #d7bd7a55;border-radius:22px;background:linear-gradient(145deg,#171d1af2,#0b100ef2);box-shadow:0 30px 90px #000c;color:#eee8d8}.hope-panel h2{margin:5px 0 8px}.hope-cards{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;margin:22px 0}.hope-card{width:140px;padding:8px;border:2px solid transparent;border-radius:14px;background:#ffffff08;color:inherit;cursor:pointer;transition:.16s}.hope-card:hover{transform:translateY(-8px);border-color:#d7bd7a88}.hope-card img{display:block;width:100%;border-radius:10px}.hope-card span{display:block;margin-top:8px;font-size:12px}.hope-order{display:flex;justify-content:center;gap:12px;align-items:flex-start;flex-wrap:wrap;margin:22px 0}.hope-order-card{width:132px;padding:8px;border-radius:12px;background:#ffffff08}.hope-order-card img{display:block;width:100%;border-radius:10px}.hope-order-card span{display:block;font-size:12px;margin-top:6px}.hope-order-buttons{display:flex;gap:5px;margin-top:7px}.hope-order-buttons button{flex:1;padding:5px}.hope-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.hope-actions button,.hope-order-buttons button{border-radius:9px;border:1px solid #d7bd7a66;background:#ffffff0d;color:inherit;cursor:pointer}.hope-actions button{padding:11px 17px}.hope-actions .primary{background:#d7bd7a;color:#17130b;font-weight:700}.hope-note{opacity:.72;line-height:1.6;text-align:center}#insight-battlefield-lock{position:fixed;inset:0;z-index:41990;background:transparent}#insight-return{position:fixed;right:22px;bottom:22px;z-index:42010;padding:12px 16px;border:1px solid #d7bd7a88;border-radius:12px;background:#171d1af2;color:#eee8d8;box-shadow:0 10px 30px #0008;cursor:pointer}`;document.head.append(style);const o=document.createElement('div');o.id='hope-insight-overlay';o.hidden=true;document.body.append(o);}
function cleanupBattlefieldView(){document.querySelector('#insight-battlefield-lock')?.remove();document.querySelector('#insight-return')?.remove();}
function close(){const o=document.querySelector('#hope-insight-overlay');if(o)o.hidden=true;cleanupBattlefieldView();active=null;}
function title(card){const d=getDefinition(card);return d.name??`${d.type} ${d.number}`;}
function cardType(card){return getDefinition(card).kind;}
function viewedCards(controller,definitionId){if(definitionId==='miracle-06')return controller.state.deck.slice(0,3);const seen=new Set(),cards=[];for(const card of controller.state.deck.slice(0,5)){cards.push(card);seen.add(cardType(card));if(seen.size>=3)break;}return cards;}
function mode(definitionId){return definitionId==='miracle-07'?{name:'行向水深之處',tag:'洞察｜新生',note:'依序展示牌庫頂，直到出現3種不同牌型（物資／神蹟／災難）或共5張。選1張加入手牌，其餘由你安排置於牌庫底。'}:{name:'所望之實底',tag:'洞察',note:'查看牌庫頂3張牌。選擇其中1張加入手牌，其餘牌再由你安排置於牌庫底。'};}
function viewBattlefield(){if(!active)return;const o=document.querySelector('#hope-insight-overlay');o.hidden=true;cleanupBattlefieldView();const lock=document.createElement('div');lock.id='insight-battlefield-lock';const back=document.createElement('button');back.id='insight-return';back.textContent=`返回${mode(active.definitionId).name}`;back.onclick=()=>{cleanupBattlefieldView();active.view?.();};document.body.append(lock,back);}
function commit(selectedId,bottomOrderIds){const p=active;if(!p)return;const cards=viewedCards(p.controller,p.definitionId),selected=cards.find(c=>c.instanceId===selectedId),m=mode(p.definitionId);close();log(p.controller,`↳ 你使用〈${m.name}〉：選擇〈${selected?title(selected):'未知牌'}〉加入手牌，其餘 ${bottomOrderIds.length} 張置於牌庫底`);previousAct.call(p.controller,{...p.action,selectedCardId:selectedId,bottomOrderIds},p.token);}
function showOrder(selectedId){const p=active;if(!p)return;const {controller,definitionId}=p,o=document.querySelector('#hope-insight-overlay'),cards=viewedCards(controller,definitionId),rest=cards.filter(c=>c.instanceId!==selectedId);let order=[...rest];const render=()=>{active.view=render;cleanupBattlefieldView();const m=mode(definitionId);o.innerHTML=`<article class="hope-panel" role="dialog" aria-modal="true"><span>神蹟 · ${m.tag}</span><h2>安排牌庫底順序</h2><p class="hope-note">左→右依序放到牌庫底。可用箭頭調整順序。此牌已打出，不能收回。</p><div class="hope-order"></div><div class="hope-actions"><button id="hope-view">查看戰場</button><button id="hope-back">返回重選</button><button class="primary" id="hope-confirm">確認</button></div></article>`;const host=o.querySelector('.hope-order');order.forEach((card,index)=>{const item=document.createElement('div');item.className='hope-order-card';item.innerHTML=`<img src="${getDefinition(card).image}" alt="${title(card)}"><span>${title(card)}</span><div class="hope-order-buttons"><button data-left ${index===0?'disabled':''}>←</button><button data-right ${index===order.length-1?'disabled':''}>→</button></div>`;item.querySelector('[data-left]').onclick=()=>{if(index<=0)return;[order[index-1],order[index]]=[order[index],order[index-1]];render();};item.querySelector('[data-right]').onclick=()=>{if(index>=order.length-1)return;[order[index],order[index+1]]=[order[index+1],order[index]];render();};host.append(item);});o.querySelector('#hope-view').onclick=viewBattlefield;o.querySelector('#hope-back').onclick=showChoose;o.querySelector('#hope-confirm').onclick=()=>commit(selectedId,order.map(c=>c.instanceId));o.hidden=false;};render();}
function showChoose(){ensureUi();const p=active;if(!p)return;const {controller,definitionId}=p,o=document.querySelector('#hope-insight-overlay'),cards=viewedCards(controller,definitionId),m=mode(definitionId);active.view=showChoose;cleanupBattlefieldView();o.innerHTML=`<article class="hope-panel" role="dialog" aria-modal="true"><span>神蹟 · ${m.tag}</span><h2>${m.name}</h2><p class="hope-note">${m.note}</p><div class="hope-cards"></div><div class="hope-actions"><button id="hope-view">查看戰場</button></div><p class="hope-note">此牌已打出，必須完成選擇後才能繼續。</p></article>`;const host=o.querySelector('.hope-cards');for(const card of cards){const b=document.createElement('button');b.className='hope-card';b.innerHTML=`<img src="${getDefinition(card).image}" alt="${title(card)}"><span>${title(card)}</span>`;b.onclick=()=>showOrder(card.instanceId);host.append(b);}o.querySelector('#hope-view').onclick=viewBattlefield;o.hidden=false;}

GameController.prototype.act=function(action,token=this.snapshot()){if(action?.type==='playMiracle'){const actor=this.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);if(actor?.type==='human'&&CARD_IDS.has(card?.definitionId)&&!action.selectedCardId){active={controller:this,action,token,definitionId:card.definitionId,view:null};showChoose();return{ok:false,pendingChoice:true,state:this.state};}}return previousAct.call(this,action,token);};
