import { GameController } from '../controller/game-controller.js';
import { getDefinition } from '../game/cards.js';
import { getNormalActions } from '../game/game.js';

const DISASTER_ID='disaster-02';
const originalRunAiTurn=GameController.prototype.runAiTurn;
let pending=null;
const humanOf=c=>c.state?.players.find(p=>p.type==='human');
const playerLabel=(s,id)=>{const p=s.players.find(x=>x.playerId===id);return p?`P${p.seat}${p.type==='human'?'（你）':''}`:id;};
const cardLabel=card=>{const d=getDefinition(card);if(d.kind==='resource'){const names={sheep:'群羊',food:'糧食',money:'金錢',grace:'恩典'};return`${names[d.type]??d.type} ${d.number}`;}return`〈${d.name}〉`;};
const log=(c,t)=>typeof c.logAi==='function'&&c.logAi(t);
function actionCard(c,a){return c.state.players.find(p=>p.playerId===a?.playerId)?.hand.find(x=>x.instanceId===a?.instanceId);}
function isLies(c,a){const card=actionCard(c,a);return !!card&&getDefinition(card).definitionId===DISASTER_ID;}
function aiRevealCard(player){return [...player.hand].sort((a,b)=>{const da=getDefinition(a),db=getDefinition(b);const va=da.kind==='resource'?(da.number??0):10,vb=db.kind==='resource'?(db.number??0):10;return va-vb;})[0];}
function aiTakeIndex(cards){let best=0,bestValue=-Infinity;cards.forEach((card,i)=>{const d=getDefinition(card),v=d.kind==='resource'?(d.number??0):(d.kind==='miracle'?11:10);if(v>bestValue){bestValue=v;best=i;}});return best;}
function ensureUi(){if(document.querySelector('#lies-choice-overlay'))return;const style=document.createElement('style');style.textContent=`#lies-choice-overlay[hidden]{display:none!important}#lies-choice-overlay{position:fixed;inset:0;z-index:36500;display:grid;place-items:center;background:#050807d8;backdrop-filter:blur(9px);padding:14px}.lies-panel{width:min(720px,94vw);max-height:92vh;overflow:auto;padding:22px;box-sizing:border-box;border:1px solid #d7bd7a66;border-radius:20px;background:linear-gradient(145deg,#18201d,#0b100e);box-shadow:0 30px 90px #000c;color:#eee8d8}.lies-panel h2{margin:5px 0 8px}.lies-panel p{opacity:.84;line-height:1.5}.lies-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:10px;margin:14px 0}.lies-card{padding:8px;border:1px solid #d7bd7a44;border-radius:12px;background:#ffffff08;color:inherit;cursor:pointer}.lies-card:hover{border-color:#d7bd7a;background:#d7bd7a18}.lies-card img{display:block;width:100%;max-height:230px;object-fit:contain;border-radius:8px;margin-bottom:6px}.lies-inspect{display:block;margin:14px auto 0;padding:10px 16px;border-radius:10px;border:1px solid #9fb5a966;background:#ffffff08;color:inherit;cursor:pointer}#lies-return{position:fixed;right:24px;bottom:24px;z-index:36400;padding:12px 18px;border-radius:12px;border:1px solid #d7bd7a;background:#17201dcc;color:#eee8d8;cursor:pointer;font-weight:700}`;document.head.append(style);const o=document.createElement('div');o.id='lies-choice-overlay';o.hidden=true;document.body.append(o);}
function close(){const o=document.querySelector('#lies-choice-overlay');if(o)o.hidden=true;document.querySelector('#lies-return')?.remove();pending=null;}
function inspectBattlefield(){const o=document.querySelector('#lies-choice-overlay');if(!o)return;o.hidden=true;let b=document.querySelector('#lies-return');if(!b){b=document.createElement('button');b.id='lies-return';b.textContent='返回〈謊言與試探〉';document.body.append(b);}b.onclick=()=>{b.remove();o.hidden=false;};}
function resolveWithHumanCard(humanCard){if(!pending)return;const {controller:c,action,targets}=pending;const cards=targets.map(p=>p.type==='human'?humanCard:aiRevealCard(p));if(cards.some(x=>!x)){close();return originalRunAiTurn.call(c,c.generation,action.playerId);}const chosenIndex=aiTakeIndex(cards),chosen=cards[chosenIndex],chosenOwner=targets[chosenIndex];log(c,`↳ ${targets.map((p,i)=>`${playerLabel(c.state,p.playerId)} 展示 ${cardLabel(cards[i])}`).join('；')}`);log(c,`↳ ${playerLabel(c.state,action.playerId)} 選擇取得 ${playerLabel(c.state,chosenOwner.playerId)} 的 ${cardLabel(chosen)}`);const finalAction={...action,targetPlayerIds:targets.map(p=>p.playerId),targetCardIds:cards.map(x=>x.instanceId),chosenCardId:chosen.instanceId};close();const result=c.act(finalAction,c.snapshot());if(result?.ok)log(c,`↳ 結果：${cardLabel(chosen)} 已移至 ${playerLabel(c.state,action.playerId)} 手牌`);else log(c,`↳ 〈謊言與試探〉未能完成：${result?.reason??'未知原因'}`);}
function showHumanReveal(c,action,targets){ensureUi();const h=humanOf(c),o=document.querySelector('#lies-choice-overlay');c.cancelTimer();pending={controller:c,action,targets};log(c,`${playerLabel(c.state,action.playerId)} 使用災難〈謊言與試探〉，目標：${targets.map(p=>playerLabel(c.state,p.playerId)).join('、')}`);o.innerHTML=`<article class="lies-panel"><span>謊言與試探 · 展示手牌</span><h2>選擇你要展示的 1 張牌</h2><p>你是這次災難的其中一名實際效果對象。遊戲會停在這裡，直到你自己選擇要展示哪張手牌；AI 不會替你選。</p><div class="lies-grid"></div><button class="lies-inspect" type="button">查看場上情況</button></article>`;const host=o.querySelector('.lies-grid');for(const card of h.hand){const d=getDefinition(card),b=document.createElement('button');b.className='lies-card';b.innerHTML=`<img src="${d.image}" alt="${cardLabel(card)}"><strong>${cardLabel(card)}</strong>`;b.onclick=()=>resolveWithHumanCard(card);host.append(b);}o.querySelector('.lies-inspect').onclick=inspectBattlefield;o.hidden=false;}
GameController.prototype.runAiTurn=function(g,pid){if(pending?.controller===this){this.cancelTimer();return;}if(g!==this.generation||!this.state||this.state.gameOver)return;const actor=this.state.players.find(p=>p.playerId===this.state.currentPlayer);if(actor?.type==='ai'&&actor.playerId===pid){const available=getNormalActions(this.state),a=available.find(x=>isLies(this,x));if(a){const targets=(a.targetPlayerIds??[]).map(id=>this.state.players.find(p=>p.playerId===id)).filter(Boolean),h=humanOf(this);if(targets.some(p=>p.playerId===h?.playerId)&&h.hand.length){showHumanReveal(this,a,targets);return;}}}return originalRunAiTurn.call(this,g,pid);};
