import { GameController } from '../controller/game-controller.js';
import { executeNormalAction, getNormalActions, settleRound } from '../game/game.js';
import { getDefinition } from '../game/cards.js';

const IMMUNITY_ID='miracle-16';
const SCAPEGOAT_ID='miracle-17';
const QA_DISASTER_ID='disaster-08';
const originalRunAiTurn=GameController.prototype.runAiTurn;
const originalPrepare=GameController.prototype.prepare;
const originalStart=GameController.prototype.start;
const originalAct=GameController.prototype.act;
let pending=null;
const humanOf=c=>c.state?.players.find(p=>p.type==='human');
const cardInHand=(p,id)=>p?.hand.find(c=>c.definitionId===id);
const hasEffect=(p,id)=>p?.effects.some(c=>c.definitionId===id);
const isDisasterAction=(controller,action)=>{if(action?.type!=='playMiracle')return false;const actor=controller.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);return !!card&&getDefinition(card).kind==='disaster';};
function affectsPlayer(action,definitionId,playerId){if(definitionId==='disaster-01')return true;if(definitionId==='disaster-02')return (action.targetPlayerIds??[]).includes(playerId);return action.targetPlayerId===playerId;}
function targetsAnotherPlayer(action,definitionId,humanId){if(definitionId==='disaster-01')return null;if(definitionId==='disaster-02')return (action.targetPlayerIds??[]).find(id=>id!==humanId)??null;return action.targetPlayerId&&action.targetPlayerId!==humanId?action.targetPlayerId:null;}
function disasterInfo(controller,action){const actor=controller.state.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);return card?{actor,card,definition:getDefinition(card)}:null;}
function purgeCard(state,instanceId){state.deck=state.deck.filter(c=>c.instanceId!==instanceId);state.discardPile=state.discardPile.filter(c=>c.instanceId!==instanceId);state.removedForRound=state.removedForRound.filter(c=>c.instanceId!==instanceId);state.playedArea=state.playedArea.filter(c=>c.instanceId!==instanceId);for(const p of state.players){p.hand=p.hand.filter(c=>c.instanceId!==instanceId);p.effects=p.effects.filter(c=>c.instanceId!==instanceId);}}
function snapshotPlayer(player,excluded){return{fire:player.fire,lowTemperatureFire:player.lowTemperatureFire,hand:structuredClone(player.hand.filter(c=>c.instanceId!==excluded?.instanceId)),effects:structuredClone(player.effects)};}
function hide(){const o=document.querySelector('#reaction-overlay');if(o)o.hidden=true;}
function finishControllerAction(controller,state){controller.state=state;controller.actionToken+=1;pending=null;hide();controller.prepare();return{ok:true,state:controller.state};}
function executeExactPending(controller,action){const result=executeNormalAction(controller.state,action);if(!result.ok){pending=null;hide();controller.prepare();return result;}return finishControllerAction(controller,result.state);}
function restoreImmunePlayer(state,playerId,snapshot,reaction){purgeCard(state,reaction.instanceId);const player=state.players.find(p=>p.playerId===playerId);player.fire=snapshot.fire;player.lowTemperatureFire=snapshot.lowTemperatureFire;player.hand=structuredClone(snapshot.hand);player.effects=structuredClone(snapshot.effects);state.playedArea.push(structuredClone(reaction));}
function executeWithHumanImmunity(controller,action){const human=humanOf(controller),reaction=cardInHand(human,IMMUNITY_ID);if(!reaction)return{ok:false,reason:'越過長夜 is no longer in hand.',state:controller.state};const snapshot=snapshotPlayer(human,reaction),result=executeNormalAction(controller.state,action);if(!result.ok)return result;restoreImmunePlayer(result.state,human.playerId,snapshot,reaction);return finishControllerAction(controller,result.state);}
function redirectedAction(action,definitionId,fromPlayerId,toPlayerId){const next=structuredClone(action);if(definitionId==='disaster-02'){next.targetPlayerIds=(next.targetPlayerIds??[]).map(id=>id===fromPlayerId?toPlayerId:id);delete next.targetCardIds;delete next.chosenCardId;}else next.targetPlayerId=toPlayerId;return next;}
function executeWithScapegoat(controller,action,originalTargetId){const human=humanOf(controller),reaction=cardInHand(human,SCAPEGOAT_ID),info=disasterInfo(controller,action);if(!reaction||!info)return{ok:false,reason:'替罪羊 is no longer available.',state:controller.state};const before=snapshotPlayer(human,reaction),redirected=redirectedAction(action,info.definition.definitionId,originalTargetId,human.playerId),result=executeNormalAction(controller.state,redirected);if(!result.ok)return result;const nextHuman=result.state.players.find(p=>p.playerId===human.playerId),lostFire=nextHuman.fire<before.fire,lostCards=nextHuman.hand.length<before.hand.length;purgeCard(result.state,reaction.instanceId);if(lostFire||lostCards)nextHuman.effects.push(structuredClone(reaction));else result.state.playedArea.push(structuredClone(reaction));return finishControllerAction(controller,result.state);}
function consumeScapegoatProtection(beforeState,afterState,humanId){const before=beforeState.players.find(p=>p.playerId===humanId),after=afterState.players.find(p=>p.playerId===humanId);if(!before||!after||!hasEffect(before,SCAPEGOAT_ID))return false;const effect=after.effects.find(c=>c.definitionId===SCAPEGOAT_ID)??before.effects.find(c=>c.definitionId===SCAPEGOAT_ID);let protectedSomething=false;if(after.fire<before.fire){const lost=before.fire-after.fire;after.fire+=Math.min(4,lost);protectedSomething=true;}else if(after.hand.length<before.hand.length){const afterIds=new Set(after.hand.map(c=>c.instanceId)),lostCards=before.hand.filter(c=>!afterIds.has(c.instanceId)&&c.instanceId!==effect.instanceId),restore=lostCards[0];if(restore){const i=afterState.discardPile.findIndex(c=>c.instanceId===restore.instanceId);if(i>=0)afterState.discardPile.splice(i,1);after.hand.push(structuredClone(restore));protectedSomething=true;}}if(protectedSomething){after.effects=after.effects.filter(c=>c.instanceId!==effect.instanceId);afterState.discardPile.push(structuredClone(effect));}return protectedSomething;}
function executeShieldedDisaster(controller,action){const human=humanOf(controller),before=structuredClone(controller.state),result=executeNormalAction(controller.state,action);if(!result.ok)return result;consumeScapegoatProtection(before,result.state,human.playerId);return finishControllerAction(controller,result.state);}
function resolveNormalReaction(controller,action,token){const actor=controller.state?.players.find(p=>p.playerId===action.playerId),card=actor?.hand.find(c=>c.instanceId===action.instanceId);if(card?.definitionId!==SCAPEGOAT_ID)return null;if(token.generation!==controller.generation||token.actionToken!==controller.actionToken)return{ok:false,reason:'Action token expired.',state:controller.state};const state=structuredClone(controller.state),player=state.players.find(p=>p.playerId===action.playerId),index=player.hand.findIndex(c=>c.instanceId===action.instanceId);if(index<0)return{ok:false,reason:'Card is not in hand.',state:controller.state};state.playedArea.push(player.hand.splice(index,1)[0]);state.currentResource=null;const currentIndex=state.players.findIndex(p=>p.playerId===player.playerId);if(state.players.filter(p=>p.hasNormalAction).length<=1){const settled=settleRound(state);if(!settled.ok)return settled;return finishControllerAction(controller,settled.state);}for(let offset=1;offset<=state.players.length;offset++){const next=(currentIndex+state.direction*offset+state.players.length)%state.players.length;if(state.players[next].hasNormalAction){state.currentPlayer=state.players[next].playerId;break;}}return finishControllerAction(controller,state);}
function ensureUi(){if(document.querySelector('#reaction-overlay'))return;const style=document.createElement('style');style.textContent=`#reaction-overlay[hidden]{display:none!important}#reaction-overlay{position:fixed;inset:0;z-index:35000;display:grid;place-items:center;background:#050807d8;backdrop-filter:blur(9px);padding:14px}.reaction-panel{width:min(560px,94vw);padding:22px;box-sizing:border-box;border:1px solid #d7bd7a66;border-radius:20px;background:linear-gradient(145deg,#18201d,#0b100e);box-shadow:0 30px 90px #000c;color:#eee8d8}.reaction-panel h2{margin:5px 0 8px}.reaction-panel p{line-height:1.55;opacity:.85}.reaction-card{display:flex;gap:16px;align-items:center;margin:16px 0;padding:12px;border:1px solid #d7bd7a44;border-radius:14px;background:#ffffff08}.reaction-card img{width:100px;max-height:145px;object-fit:contain;border-radius:7px}.reaction-actions{display:flex;gap:10px;justify-content:center}.reaction-actions button{padding:11px 18px;border-radius:11px;border:1px solid #d7bd7a66;background:#ffffff0d;color:inherit;cursor:pointer}.reaction-actions .use{background:#d7bd7a26;border-color:#d7bd7a}`;document.head.append(style);const o=document.createElement('div');o.id='reaction-overlay';o.hidden=true;document.body.append(o);}
function showImmunity(controller,action){ensureUi();const info=disasterInfo(controller,action),human=humanOf(controller),reaction=cardInHand(human,IMMUNITY_ID),o=document.querySelector('#reaction-overlay');if(!info||!reaction)return false;controller.cancelTimer();pending={controller,action};o.innerHTML=`<article class="reaction-panel"><span>【應對】時機</span><h2>${info.definition.name} 即將影響你</h2><p>你持有《越過長夜》。現在可以打出它，使你免疫這一次災難效果。</p><div class="reaction-card"><img src="${getDefinition(reaction).image}" alt="越過長夜"><div><strong>越過長夜</strong><p>你免疫該次災難效果。</p></div></div><div class="reaction-actions"><button class="use" id="reaction-use">打出《越過長夜》</button><button id="reaction-pass">不應對</button></div></article>`;o.querySelector('#reaction-use').onclick=()=>executeWithHumanImmunity(controller,action);o.querySelector('#reaction-pass').onclick=()=>executeExactPending(controller,action);o.hidden=false;return true;}
function showScapegoat(controller,action,targetId){ensureUi();const info=disasterInfo(controller,action),human=humanOf(controller),reaction=cardInHand(human,SCAPEGOAT_ID),target=controller.state.players.find(p=>p.playerId===targetId),o=document.querySelector('#reaction-overlay');if(!info||!reaction||!target)return false;controller.cancelTimer();pending={controller,action};o.innerHTML=`<article class="reaction-panel"><span>【應對】時機</span><h2>${info.definition.name} 即將影響 P${target.seat}</h2><p>你持有《替罪羊》。你可以把這次災難原本對 P${target.seat} 的效果轉移給自己；轉移後你不能用免疫取消它。</p><div class="reaction-card"><img src="${getDefinition(reaction).image}" alt="替罪羊"><div><strong>替罪羊</strong><p>若你因此失去火種或棄牌，此牌會留在效果區，抵減你下一次災難損失。</p></div></div><div class="reaction-actions"><button class="use" id="reaction-use">打出《替罪羊》</button><button id="reaction-pass">不應對</button></div></article>`;o.querySelector('#reaction-use').onclick=()=>executeWithScapegoat(controller,action,targetId);o.querySelector('#reaction-pass').onclick=()=>executeExactPending(controller,action);o.hidden=false;return true;}
function moveDefinitionToPlayer(state,definitionId,target){if(target.hand.some(c=>c.definitionId===definitionId))return;let incoming=null,source=null;const deckIndex=state.deck.findIndex(c=>c.definitionId===definitionId);if(deckIndex>=0){incoming=state.deck.splice(deckIndex,1)[0];source=state.deck;}if(!incoming){for(const player of state.players.filter(p=>p!==target)){const index=player.hand.findIndex(c=>c.definitionId===definitionId);if(index>=0){incoming=player.hand.splice(index,1)[0];source=player.hand;break;}}}if(!incoming)return;const replaceIndex=target.hand.findIndex(c=>![SCAPEGOAT_ID,QA_DISASTER_ID].includes(c.definitionId));const replaced=replaceIndex>=0?target.hand.splice(replaceIndex,1,incoming)[0]:target.hand.pop();if(replaceIndex<0)target.hand.push(incoming);if(replaced)source.push(replaced);}
function guaranteePreviewSetup(controller){if(controller.state?.qaSeed!=='recovery-preview'||controller.state.round!==1)return;const state=controller.state,human=humanOf(controller),ai=state.players.find(p=>p.type==='ai');human.fire=10;moveDefinitionToPlayer(state,SCAPEGOAT_ID,human);const old=human.hand.find(c=>c.definitionId===IMMUNITY_ID);if(old){human.hand=human.hand.filter(c=>c.instanceId!==old.instanceId);state.deck.push(old);}if(ai){ai.fire=10;moveDefinitionToPlayer(state,QA_DISASTER_ID,ai);}}
GameController.prototype.start=function(seed){originalStart.call(this,seed);guaranteePreviewSetup(this);this.safeRender(getNormalActions(this.state));return this.state;};
GameController.prototype.act=function(action,token=this.snapshot()){const special=resolveNormalReaction(this,action,token);return special??originalAct.call(this,action,token);};
GameController.prototype.prepare=function(){if(pending?.controller===this){this.cancelTimer();this.safeRender(getNormalActions(this.state));return;}return originalPrepare.call(this);};
GameController.prototype.runAiTurn=function(generation,playerId){if(pending?.controller===this){this.cancelTimer();return;}if(generation!==this.generation||!this.state||this.state.gameOver)return;const actor=this.state.players.find(p=>p.playerId===this.state.currentPlayer);if(actor?.type==='ai'&&actor.playerId===playerId){const actions=getNormalActions(this.state);let action=actions.find(a=>isDisasterAction(this,a));if(this.state.qaSeed==='recovery-preview'){const qa=actions.find(a=>{if(!isDisasterAction(this,a))return false;const info=disasterInfo(this,a);return info?.definition.definitionId===QA_DISASTER_ID&&a.targetPlayerId!==humanOf(this)?.playerId;});if(qa)action=qa;}action=action??actions[0];if(action&&isDisasterAction(this,action)){const info=disasterInfo(this,action),human=humanOf(this),otherTarget=targetsAnotherPlayer(action,info.definition.definitionId,human.playerId);if(cardInHand(human,SCAPEGOAT_ID)&&otherTarget){showScapegoat(this,action,otherTarget);return;}if(cardInHand(human,IMMUNITY_ID)&&affectsPlayer(action,info.definition.definitionId,human.playerId)){showImmunity(this,action);return;}if(hasEffect(human,SCAPEGOAT_ID)&&affectsPlayer(action,info.definition.definitionId,human.playerId)){if(info.definition.definitionId==='disaster-01')return originalRunAiTurn.call(this,generation,playerId);executeShieldedDisaster(this,action);return;}}
if(action&&action!==actions[0]){const result=executeNormalAction(this.state,action);if(result.ok){this.state=result.state;this.actionToken+=1;this.prepare();}return;}}
return originalRunAiTurn.call(this,generation,playerId);};
