import { GameController } from '../controller/game-controller.js';
import { getDefinition } from '../game/cards.js';

const previousSafeRender = GameController.prototype.safeRender;
const OVERLAY_ID = 'rebuild-choice-overlay';
const RETURN_ID = 'rebuild-choice-return';

function title(card){const d=getDefinition(card);return d.name??`${{sheep:'群羊',food:'糧食',money:'金錢',grace:'恩典'}[d.type]??d.type} ${d.number}`;}
function ensureStyle(){if(document.querySelector('#rebuild-choice-style'))return;const s=document.createElement('style');s.id='rebuild-choice-style';s.textContent=`#${OVERLAY_ID}{position:fixed;inset:0;z-index:42000;display:grid;place-items:center;background:#050807d6;backdrop-filter:blur(9px);padding:16px}#${OVERLAY_ID}[hidden]{display:none!important}.rebuild-panel{width:min(900px,95vw);max-height:90vh;overflow:auto;padding:24px;border:1px solid #d7bd7a66;border-radius:22px;background:linear-gradient(145deg,#18201d,#0b100e);box-shadow:0 30px 90px #000c;color:#eee8d8}.rebuild-panel h2{margin:5px 0 8px}.rebuild-note{opacity:.78;line-height:1.6}.rebuild-cards{display:flex;justify-content:center;gap:12px;flex-wrap:wrap;margin:20px 0}.rebuild-card{width:126px;padding:7px;border:1px solid #d7bd7a55;border-radius:12px;background:#ffffff08;color:inherit;cursor:pointer;transition:.15s}.rebuild-card:hover{transform:translateY(-6px);border-color:#d7bd7a}.rebuild-card img{display:block;width:100%;border-radius:8px}.rebuild-card span{display:block;margin-top:6px;font-size:12px}.rebuild-actions{display:flex;justify-content:center;gap:10px}.rebuild-actions button,#${RETURN_ID}{padding:10px 16px;border-radius:10px;border:1px solid #9fb5a966;background:#ffffff0d;color:#eee8d8;cursor:pointer}#${RETURN_ID}{position:fixed;right:24px;bottom:24px;z-index:43000;background:#17201dee;font-weight:700}`;document.head.append(s);}
function hideForInspect(){const o=document.querySelector(`#${OVERLAY_ID}`);if(!o)return;o.hidden=true;let b=document.querySelector(`#${RETURN_ID}`);if(!b){b=document.createElement('button');b.id=RETURN_ID;b.textContent='返回《拆毀後重建》';document.body.append(b);}b.onclick=()=>{b.remove();o.hidden=false;};}
function renderPending(controller,available){const pending=controller.state?.pendingRebuild,human=controller.state?.players.find(p=>p.type==='human');document.querySelector(`#${RETURN_ID}`)?.remove();if(!pending||pending.playerId!==human?.playerId){document.querySelector(`#${OVERLAY_ID}`)?.remove();return;}ensureStyle();let o=document.querySelector(`#${OVERLAY_ID}`);if(!o){o=document.createElement('div');o.id=OVERLAY_ID;document.body.append(o);}const stage=pending.stage;let heading='',note='';if(stage==='discardInitial'){heading='先棄置 1 張手牌';note='《拆毀後重建》已成功打出，現在必須完成效果。棄置後，查看棄牌區最上方至多 5 張牌。';}else if(stage==='chooseDiscard'){heading='從棄牌區重建';note='選擇剛才查看的其中 1 張牌加入手牌。若選到神蹟或災難，之後還要再棄置 1 張手牌。';}else{heading='再棄置 1 張手牌';note='你取回的是神蹟或災難，因此必須再棄置 1 張手牌完成結算。';}
o.innerHTML=`<article class="rebuild-panel" role="dialog" aria-modal="true"><span>神蹟 · 洞察｜新生</span><h2>${heading}</h2><p class="rebuild-note">${note}</p><div class="rebuild-cards"></div><div class="rebuild-actions"><button id="rebuild-inspect">查看戰場</button></div></article>`;const host=o.querySelector('.rebuild-cards');for(const action of available){let card=null;if(stage==='chooseDiscard'){card=controller.state.discardPile.find(c=>c.instanceId===action.selectedCardId);}else{card=human.hand.find(c=>c.instanceId===action.discardInstanceId);}if(!card)continue;const d=getDefinition(card),b=document.createElement('button');b.className='rebuild-card';b.innerHTML=`<img src="${d.image}" alt="${title(card)}"><span>${title(card)}</span>`;b.onclick=()=>controller.act(action,controller.snapshot());host.append(b);}o.querySelector('#rebuild-inspect').onclick=hideForInspect;o.hidden=false;}

GameController.prototype.safeRender=function patchedRebuildSafeRender(available){const result=previousSafeRender.call(this,available);try{renderPending(this,available??[]);}catch(error){console.error('[Shepherd] rebuild-choice render failed; gameplay will continue.',error);}return result;};
