import { createPlayableGame, legalActions, playCard, prepare, skipNoLegalAction, runAiTurn, resolveAuction, activeJudgments, CHARACTER_POOL, RESOURCE_TYPES, LABEL } from './src/playable/game.js';

const $=s=>document.querySelector(s);let state=null,selected=null,aiTimer=null,forcedSkipTimer=null,audioStarted=false;
const el={hand:$('#hand'),detail:$('#detail-content'),corruption:$('#corruption-value'),fill:$('#corruption-fill'),judgments:$('#judgment-strip'),round:$('#round-pill'),phase:$('#phase-copy'),current:$('#current-card'),apostle:$('#apostle'),direction:$('#direction'),jackpot:$('#jackpot'),roundSummary:$('#round-summary'),prepare:$('#prepare'),overlay:$('#overlay'),modal:$('#modal'),toast:$('#toast'),log:$('#log-list'),logPanel:$('#log-panel'),bgm:$('#bgm')};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');setTimeout(()=>el.toast.classList.remove('show'),1400)}
function pct(n,d){return d?Math.min(100,Math.round(n/d*100)):0}
function missionHtml(p){if(!p.mission)return'<div class="seat-char">最終輪 · 無一般使命</div>';return`<div class="mission-row">${RESOURCE_TYPES.map(t=>`<div class="mission-bit">${LABEL[t]} ${p.missionProgress[t]}/${p.mission[t]}<div class="mission-bar"><i style="width:${pct(p.missionProgress[t],p.mission[t])}%"></i></div></div>`).join('')}</div>`}
function seatHtml(p){const isCurrent=state.currentPlayer===p.id;return`<div class="seat-card ${isCurrent?'current':''}"><div class="seat-head"><span class="seat-name">${esc(p.name)}</span><span class="seat-stats">🔥 ${p.fire} · 🃏 ${p.hand.length}</span></div><div class="seat-char">${esc(p.character?.faction||'')} · ${esc(p.character?.name||'')} · 使命 ${p.completedMissions}${p.qualified?' ✓':''}</div>${missionHtml(p)}<div class="seat-foot">${p.blessings.map(b=>`<span class="mini-chip">${esc(b.name)}</span>`).join('')}${p.effects.map(e=>`<span class="mini-chip">${esc(e.id)}</span>`).join('')}</div></div>`}
function phaseCopy(){if(state.gameOver)return'爭局已結束';if(state.phase==='auction')return'火種精靈正在進行祝福競拍';if(state.phase==='death-round')return'死亡輪 · 每人最後一次正常行動';const p=state.players.find(x=>x.id===state.currentPlayer);return p?.human?'輪到你行動':'等待其他玩家行動'}
function isBlind(){return activeJudgments(state).find(j=>j.id==='blindness-1'||j.id==='blindness-2')}
function playableIds(){return new Set(legalActions(state,'p1').filter(a=>a.type==='play').map(a=>a.cardId))}
function renderHand(){const p=state.players[0],playable=playableIds(),blind=isBlind();el.hand.innerHTML='';p.hand.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.dataset.cardId=c.id;b.className=`game-card ${playable.has(c.id)?'':'illegal'}`;b.style.setProperty('--r',`${(i-(p.hand.length-1)/2)*1.1}deg`);const hide=blind&&c.type!=='resource';if(hide){const label=blind.id==='blindness-2'?'未知功能牌':c.type==='miracle'?'未知神蹟':'未知災難';b.innerHTML=`<div class="card-back">${label}</div><span class="corrupt-badge">?</span>`;}else{b.innerHTML=`<img src="${c.image}" alt="${esc(c.name)}"><span class="corrupt-badge">${c.corruption||0}</span>`;}el.hand.appendChild(b);});}
function cardDetailHtml(c){const blind=isBlind();if(blind&&c.type!=='resource')return `<h2>${blind.id==='blindness-2'?'未知功能牌':c.type==='miracle'?'未知神蹟':'未知災難'}</h2><p>【蒙蔽】使你無法確認這張牌的具體內容。</p>`;return `<div class="long-card-detail"><img src="${c.image}" alt=""><div><h2>${esc(c.name)}</h2><p>${esc(c.text||`${LABEL[c.resourceType]||'物資'} · 原始數字 ${c.printedNumber}`)}</p><div class="tags"><span class="tag">${c.type==='resource'?'物資':c.type==='miracle'?'神蹟':'災難'}</span><span class="tag">崩壞 ${c.corruption||0}</span>${c.printedNumber?`<span class="tag">原始數字 ${c.printedNumber}</span>`:''}</div></div></div>`}
function openCardDetail(c){el.modal.innerHTML=`${cardDetailHtml(c)}<div class="modal-actions"><button class="ghost" data-close-detail>關閉</button>${playableIds().has(c.id)?'<button class="primary" data-play-detail>打出此牌</button>':''}</div>`;el.overlay.classList.remove('hidden');el.modal.querySelector('[data-close-detail]').onclick=()=>el.overlay.classList.add('hidden');el.modal.querySelector('[data-play-detail]')?.addEventListener('click',()=>{el.overlay.classList.add('hidden');requestPlay(c)})}
function cardById(id){return state?.players?.[0]?.hand?.find(c=>c.id===id)||null}
function randomBlindCard(c){const blind=isBlind();if(!blind||c.type==='resource')return c;const p=state.players[0];const pool=blind.id==='blindness-2'?p.hand.filter(x=>x.type!=='resource'):p.hand.filter(x=>x.type===c.type);return pool[Math.floor(Math.random()*pool.length)]||c}
function requiresTarget(c){return c.target==='single'||c.target==='multi'||['victory','bird','cup','overflow'].includes(c.effect)}
function requestPlay(raw){if(state.currentPlayer!=='p1'){toast('還沒輪到你');return}const c=randomBlindCard(raw);if(c.type==='resource'&&c.resourceType==='grace'){openChoice('恩典化為物資','選擇本次恩典視為哪種物資。',RESOURCE_TYPES.map(t=>({id:t,name:LABEL[t]})),id=>commitPlay(c,{declared:id}));return}if(c.effect==='wind'){openChoice('如風吹來','選擇本次效果。',[{id:'fire',name:'獲得 4 火種'},{id:'cycle',name:'棄 1 張並抽 1 張'}],id=>commitPlay(c,{mode:id,count:1}));return}if(c.effect==='overflow'){chooseTarget(c,targetId=>openChoice('杯滿盈溢','你要取得哪一項？',[{id:'mission',name:'使命 +3'},{id:'draw',name:'抽 1 張'}],mode=>commitPlay(c,{targetId,mode})));return}if(requiresTarget(c)){chooseTarget(c,choice=>commitPlay(c,Array.isArray(choice)?{targetIds:choice}:{targetId:choice}));return}commitPlay(c,{});}
function chooseTarget(c,done){const others=state.players.filter(p=>p.id!=='p1');const multi=c.target==='multi';openChoice(multi?'選擇兩名目標':'選擇目標',c.name,others.map(p=>({id:p.id,name:p.name,sub:`🔥${p.fire} · 手牌 ${p.hand.length}`})),id=>{if(!multi)done(id);else{const second=others.find(p=>p.id!==id)?.id;done([id,second].filter(Boolean));}})}
function commitPlay(c,choice){try{playCard(state,'p1',c.id,choice);selected=null;render();scheduleAI()}catch(e){toast(e.message);render()}}
function openChoice(title,copy,choices,done){el.modal.innerHTML=`<h2>${esc(title)}</h2><p>${esc(copy)}</p><div class="choice-grid">${choices.map(x=>`<button class="choice" data-id="${x.id}"><strong>${esc(x.name)}</strong>${x.sub?`<small>${esc(x.sub)}</small>`:''}</button>`).join('')}</div><div class="modal-actions"><button class="ghost" data-cancel>取消</button></div>`;el.overlay.classList.remove('hidden');el.modal.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{el.overlay.classList.add('hidden');done(b.dataset.id)});el.modal.querySelector('[data-cancel]').onclick=()=>el.overlay.classList.add('hidden')}
function renderPlayedPile(){const pile=$('#played-pile');if(!pile)return;const recent=state.played.slice(-3);pile.innerHTML=recent.map((c,i)=>`<div class="pile-card-v2" style="--pile-i:${i};--pile-r:${[-7,4,-2][i]||0}deg;--pile-x:${[-18,12,0][i]||0}px;--pile-y:${[8,5,-3][i]||0}px"><img src="${c.image||''}" alt="${esc(c.name||'已出牌')}"></div>`).join('');el.current.classList.toggle('empty',recent.length===0);el.current.innerHTML=recent.length?'':'<span>尚無出牌</span>'}
function render(){if(!state)return;state.players.forEach(p=>{$(`#seat-${p.id}`).innerHTML=seatHtml(p)});el.round.textContent=`第 ${state.round} / 7 輪`;el.phase.textContent=phaseCopy();el.corruption.textContent=`${state.corruption} / ${state.threshold}`;el.fill.style.width=`${Math.min(100,state.corruption/state.threshold*100)}%`;el.judgments.innerHTML=activeJudgments(state).map(j=>`<span class="judgment-chip" title="${esc(j.text)}">${esc(j.name)}</span>`).join('')||'<span class="muted" style="font-size:9px">世界尚未受到審判</span>';el.jackpot.textContent=state.played.length;el.apostle.textContent=`使徒 · ${state.currentApostle?state.players.find(p=>p.id===state.currentApostle)?.name:'尚無'}`;el.direction.textContent=state.direction===1?'順時針':'逆時針';el.roundSummary.innerHTML=`<div>${state.round<=6?'使命試煉':'最終使徒爭奪'}</div><div>審判累計：${state.totalJudgments}</div><div>牌庫：${state.deck.length} 張</div>${state.death.triggered?'<div style="color:#e68b72">死亡已揭示</div>':''}`;renderPlayedPile()el.prepare.disabled=state.currentPlayer!=='p1'||state.phase!=='actions'||!legalActions(state,'p1').some(a=>a.type==='prepare');renderHand();renderLog();scheduleForcedHumanSkip();if(state.phase==='auction')renderAuction();if(state.gameOver)renderFinal();}
function scheduleForcedHumanSkip(){clearTimeout(forcedSkipTimer);if(!state||state.gameOver||state.currentPlayer!=='p1'||state.phase!=='death-round')return;if(legalActions(state,'p1').some(a=>a.type==='play'))return;forcedSkipTimer=setTimeout(()=>{if(!state||state.gameOver||state.currentPlayer!=='p1'||state.phase!=='death-round'||legalActions(state,'p1').some(a=>a.type==='play'))return;toast('死亡輪沒有合法牌，最後行動自動略過');skipNoLegalAction(state,'p1');selected=null;render();scheduleAI()},500)}
function renderLog(){el.log.innerHTML=state.log.map(x=>`<div class="log-item ${x.type}"><b>R${x.round}</b> ${esc(x.msg)}</div>`).join('')}
function renderAuction(){if(!state.auction)return;const h=state.players[0];el.modal.innerHTML=`<h2>火種精靈 · 祝福競拍</h2><p>所有玩家同時選擇目標並出價。測試版採一次提交、同價時目前火種較少者優先。</p><div class="choice-grid">${state.auction.options.map((b,i)=>`<button class="choice auction-card ${i===0?'selected':''}" data-bid-target="${b.id}"><strong>${esc(b.name)}</strong><small>${esc(b.text)}</small></button>`).join('')}</div><div class="bid-row"><span>出價</span><input id="bid" type="range" min="0" max="${h.fire}" value="${Math.min(4,h.fire)}"><strong id="bid-value">${Math.min(4,h.fire)}</strong></div><div class="modal-actions"><button id="bid-submit" class="primary">提交競拍</button></div>`;el.overlay.classList.remove('hidden');let target=state.auction.options[0].id;el.modal.querySelectorAll('[data-bid-target]').forEach(b=>b.onclick=()=>{target=b.dataset.bidTarget;el.modal.querySelectorAll('[data-bid-target]').forEach(x=>x.classList.toggle('selected',x===b))});const r=$('#bid'),v=$('#bid-value');r.oninput=()=>v.textContent=r.value;$('#bid-submit').onclick=()=>{el.overlay.classList.add('hidden');resolveAuction(state,{blessingId:target,bid:Number(r.value)});render();scheduleAI()}}
function renderFinal(){const w=state.players.find(p=>p.id===state.final?.winnerId);el.modal.innerHTML=`<h2>${w?.id==='p1'?'你贏得了荒野爭局':'荒野爭局結束'}</h2><p>${esc(state.final?.reason||'')}</p><div class="final-score">${state.players.map(p=>`<div class="final-person ${p.id===w?.id?'winner':''}"><strong>${esc(p.name)}</strong><div>使命 ${p.completedMissions}</div><div>火種 ${p.fire}</div><div>${p.qualified?'已取得資格':'未取得資格'}</div></div>`).join('')}</div><div class="modal-actions"><button id="again" class="primary">再來一局</button></div>`;el.overlay.classList.remove('hidden');$('#again').onclick=()=>setupModal()}
function scheduleAI(){clearTimeout(aiTimer);if(!state||state.gameOver||state.phase==='auction')return;const p=state.players.find(x=>x.id===state.currentPlayer);if(p?.human)return;aiTimer=setTimeout(()=>{try{runAiTurn(state)}catch(e){console.error(e);toast('AI 行動錯誤：'+e.message)}render();scheduleAI()},420)}
function setupModal(){clearTimeout(aiTimer);const chars=CHARACTER_POOL.map((c,i)=>`<button class="choice character-option ${i===0?'selected':''}" data-character="${c.id}"><strong>${esc(c.name)}</strong><small>${esc(c.faction)}</small></button>`).join('');el.modal.innerHTML=`<h2>建立 PvP V2 測試爭局</h2><p>真人 1 名＋高階規則 AI ×3。美術與荒野音樂沿用原版資產；崩壞臨界值仍未正式定案，可在這裡調整。</p><div class="setup-grid"><div><div class="panel-title">選擇人物</div><div class="character-grid">${chars}</div></div><div><div class="field"><label>崩壞臨界值</label><input id="threshold" type="number" min="15" max="60" value="30"></div><div class="field"><label>測試 Seed</label><input id="seed" value="v2-${Date.now().toString().slice(-5)}"></div><button id="start" class="primary" style="width:100%;margin-top:8px">開始爭局</button></div></div>`;el.overlay.classList.remove('hidden');let character=CHARACTER_POOL[0].id;el.modal.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{character=b.dataset.character;el.modal.querySelectorAll('[data-character]').forEach(x=>x.classList.toggle('selected',x===b))});$('#start').onclick=()=>{state=createPlayableGame({seed:$('#seed').value||'v2',threshold:Number($('#threshold').value)||30,humanCharacter:character});selected=null;el.overlay.classList.add('hidden');render();scheduleAI();startAudio()}}
function startAudio(){if(audioStarted)return;audioStarted=true;el.bgm.volume=.34;el.bgm.play().catch(()=>{audioStarted=false})}
window.addEventListener('shepherd:v2-play-card',e=>{const c=cardById(e.detail?.cardId);if(c)requestPlay(c)});
window.addEventListener('shepherd:v2-card-detail',e=>{const c=cardById(e.detail?.cardId);if(c)openCardDetail(c)});
el.prepare.onclick=()=>{try{prepare(state,'p1');selected=null;render();scheduleAI()}catch(e){toast(e.message)}};$('#restart').onclick=()=>setupModal();$('#toggle-log').onclick=()=>el.logPanel.classList.remove('hidden');$('#close-log').onclick=()=>el.logPanel.classList.add('hidden');$('#audio-toggle').onclick=()=>{if(el.bgm.paused){el.bgm.play();$('#audio-toggle').textContent='♫ 音樂'}else{el.bgm.pause();$('#audio-toggle').textContent='♫ 靜音'}};document.addEventListener('keydown',e=>{if(e.key==='Escape')el.overlay.classList.add('hidden')});
setupModal();
