import test from 'node:test';import assert from 'node:assert/strict';import {createGame,executeNormalAction,getNormalActions,listCardLocations} from '../src/game/game.js';import {getDefinition,RESOURCE_TYPES} from '../src/game/cards.js';
const resourceCards=p=>p.hand.filter(c=>{const d=getDefinition(c);return d.kind==='resource'&&RESOURCE_TYPES.includes(d.type);});
function choicesFor(state){return Object.fromEntries(state.players.map(p=>{const cards=resourceCards(p);if(!cards.length)return[p.playerId,{keepType:null,discardIds:[]}];const keepType=getDefinition(cards[0]).type,eligible=cards.filter(c=>getDefinition(c).type!==keepType);return[p.playerId,{keepType,discardIds:eligible.slice(0,Math.min(2,eligible.length)).map(c=>c.instanceId)}];}));}
test('preview QA guarantees only current group disaster',()=>{const state=createGame({seed:'recovery-preview'});assert.deepEqual(state.players.map(p=>p.fire),[0,0,0,0]);assert.equal(state.players[0].hand.length,7);assert.ok(state.players[0].hand.some(c=>c.definitionId==='disaster-01'));assert.equal(state.players[0].hand.some(c=>c.definitionId==='disaster-02'),false);assert.equal(state.players[0].hand.some(c=>c.definitionId==='miracle-10'),false);});
test('方舟之外 is a targetless group action',()=>{const state=createGame({seed:'group-action'});state.currentPlayer='player-1';const card=state.players[0].hand.find(c=>c.definitionId==='disaster-01'),action=getNormalActions(state).find(a=>a.instanceId===card.instanceId);assert.ok(action);assert.equal(action.targetPlayerId,undefined);assert.equal(action.targetPlayerIds,undefined);});
test('方舟之外 discards only non-kept ordinary resources and never miracle disaster or grace',()=>{const state=createGame({seed:'group-resolve'});state.currentPlayer='player-1';const card=state.players[0].hand.find(c=>c.definitionId==='disaster-01'),action=getNormalActions(state).find(a=>a.instanceId===card.instanceId),choices=choicesFor(state),protectedIds=state.players.flatMap(p=>p.hand.filter(c=>{const d=getDefinition(c);return d.kind!=='resource'||d.type==='grace';}).map(c=>c.instanceId)).filter(id=>id!==card.instanceId),discardIds=Object.values(choices).flatMap(c=>c.discardIds),result=executeNormalAction(state,{...action,groupChoices:choices});assert.equal(result.ok,true,result.reason);for(const id of protectedIds)assert.ok(result.state.players.some(p=>p.hand.some(c=>c.instanceId===id)));for(const id of discardIds)assert.ok(result.state.discardPile.some(c=>c.instanceId===id));assert.ok(result.state.playedArea.some(c=>c.instanceId===card.instanceId));});
test('方舟之外 rejects discarding a kept resource',()=>{const state=createGame({seed:'group-invalid'});state.currentPlayer='player-1';const card=state.players[0].hand.find(c=>c.definitionId==='disaster-01'),action=getNormalActions(state).find(a=>a.instanceId===card.instanceId),choices=choicesFor(state),p=state.players.find(p=>resourceCards(p).length>1);if(!p)return;const kept=resourceCards(p)[0],type=getDefinition(kept).type;choices[p.playerId]={keepType:type,discardIds:[kept.instanceId]};const result=executeNormalAction(state,{...action,groupChoices:choices});assert.equal(result.ok,false);assert.equal(result.state,state);});
test('AI resolver can choose for every player without UI fields',()=>{const state=createGame({seed:'group-ai'}),card=state.players[0].hand.find(c=>c.definitionId==='disaster-01');state.players[0].hand=state.players[0].hand.filter(c=>c.instanceId!==card.instanceId);state.players[1].hand.unshift(card);state.currentPlayer='player-2';const action=getNormalActions(state).find(a=>a.instanceId===card.instanceId),result=executeNormalAction(state,action);assert.equal(result.ok,true,result.reason);assert.ok(result.state.playedArea.some(c=>c.instanceId===card.instanceId));});
test('方舟之外 preserves card location invariant',()=>{const state=createGame({seed:'group-invariant'});state.currentPlayer='player-1';const card=state.players[0].hand.find(c=>c.definitionId==='disaster-01'),action=getNormalActions(state).find(a=>a.instanceId===card.instanceId),result=executeNormalAction(state,action),locations=listCardLocations(result.state);assert.equal(result.ok,true,result.reason);assert.equal(new Set(locations).size,locations.length);assert.equal(locations.length,Object.keys(result.state.cardRegistry).length);});
