import test from 'node:test';import assert from 'node:assert/strict';import {createGame,executeNormalAction,getNormalActions,listCardLocations} from '../src/game/game.js';
function setup(seed='exchange-test'){const state=createGame({seed});state.currentPlayer='player-1';const miracle=state.players[0].hand.find(c=>c.definitionId==='miracle-10');return{state,miracle};}
test('exchange QA restores zero fire and guarantees only current miracle',()=>{const{state}=setup();assert.deepEqual(state.players.map(p=>p.fire),[0,0,0,0]);assert.equal(state.players[0].hand.length,7);assert.ok(state.players[0].hand.some(c=>c.definitionId==='miracle-10'));assert.equal(state.players[0].hand.some(c=>c.definitionId==='disaster-08'),false);});
test('恰如飛鳥經過 exposes other players with cards as targets',()=>{const{state,miracle}=setup('exchange-targets');const actions=getNormalActions(state).filter(a=>a.instanceId===miracle.instanceId);assert.deepEqual(new Set(actions.map(a=>a.targetPlayerId)),new Set(['player-2','player-3','player-4']));});
test('agreed exchange swaps selected cards and puts miracle in played area',()=>{const{state,miracle}=setup('exchange-agree');const own=state.players[0].hand.find(c=>c.instanceId!==miracle.instanceId),theirs=state.players[1].hand[0];const action=getNormalActions(state).find(a=>a.instanceId===miracle.instanceId&&a.targetPlayerId==='player-2');const result=executeNormalAction(state,{...action,selectedOwnCardId:own.instanceId,targetCardId:theirs.instanceId,consent:true});assert.equal(result.ok,true,result.reason);assert.ok(result.state.players[0].hand.some(c=>c.instanceId===theirs.instanceId));assert.ok(result.state.players[1].hand.some(c=>c.instanceId===own.instanceId));assert.ok(result.state.playedArea.some(c=>c.instanceId===miracle.instanceId));assert.equal(result.state.currentResource,null);});
test('refused exchange returns shown cards but still resolves miracle',()=>{const{state,miracle}=setup('exchange-refuse');const own=state.players[0].hand.find(c=>c.instanceId!==miracle.instanceId),theirs=state.players[1].hand[0];const action=getNormalActions(state).find(a=>a.instanceId===miracle.instanceId&&a.targetPlayerId==='player-2');const result=executeNormalAction(state,{...action,selectedOwnCardId:own.instanceId,targetCardId:theirs.instanceId,consent:false});assert.equal(result.ok,true);assert.ok(result.state.players[0].hand.some(c=>c.instanceId===own.instanceId));assert.ok(result.state.players[1].hand.some(c=>c.instanceId===theirs.instanceId));assert.ok(result.state.playedArea.some(c=>c.instanceId===miracle.instanceId));});
test('different exchanged card types award both players 3 fire',()=>{const{state,miracle}=setup('exchange-fire');const sheep=state.deck.find(c=>c.definitionId==='sheep-1'),food=state.deck.find(c=>c.definitionId==='food-1');state.deck=state.deck.filter(c=>c.instanceId!==sheep.instanceId&&c.instanceId!==food.instanceId);state.players[0].hand=[miracle,sheep];state.players[1].hand=[food];const action=getNormalActions(state).find(a=>a.instanceId===miracle.instanceId&&a.targetPlayerId==='player-2');const result=executeNormalAction(state,{...action,selectedOwnCardId:sheep.instanceId,targetCardId:food.instanceId,consent:true});assert.equal(result.ok,true);assert.equal(result.state.players[0].fire,3);assert.equal(result.state.players[1].fire,3);});
test('same exchanged card types award no fire',()=>{const{state,miracle}=setup('exchange-same');const cards=state.deck.filter(c=>c.definitionId.startsWith('sheep-')).slice(0,2);state.deck=state.deck.filter(c=>!cards.some(x=>x.instanceId===c.instanceId));state.players[0].hand=[miracle,cards[0]];state.players[1].hand=[cards[1]];const action=getNormalActions(state).find(a=>a.instanceId===miracle.instanceId&&a.targetPlayerId==='player-2');const result=executeNormalAction(state,{...action,selectedOwnCardId:cards[0].instanceId,targetCardId:cards[1].instanceId,consent:true});assert.equal(result.ok,true);assert.equal(result.state.players[0].fire,0);assert.equal(result.state.players[1].fire,0);});
test('AI can resolve exchange action without UI-only fields and card invariant survives',()=>{const{state,miracle}=setup('exchange-ai');state.players[0].hand=state.players[0].hand.filter(c=>c.instanceId!==miracle.instanceId);state.players[1].hand.push(miracle);state.currentPlayer='player-2';const action=getNormalActions(state).find(a=>a.instanceId===miracle.instanceId&&a.targetPlayerId==='player-1');const result=executeNormalAction(state,action);assert.equal(result.ok,true,result.reason);const ids=listCardLocations(result.state);assert.equal(ids.length,new Set(ids).size);assert.equal(ids.length,Object.keys(result.state.cardRegistry).length);});
